pipeline {
    agent any

    stages {

        stage('SonarQube Analysis') {
            steps {
                dir('complete') {
                    withSonarQubeEnv('Sq1') {
                        sh './mvnw sonar:sonar'
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('complete') {
                    sh '''
                        ./mvnw clean package -DskipTests
                        docker build -t greeting-app:latest .
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop greeting-app || true
                    docker rm greeting-app || true
                    docker run -d --name greeting-app -p 8081:8080 greeting-app:latest
                '''
            }
        }
    }
}
